Repository Financial-Times/origami-image-service, pull requests merged in 2021-11, with the labels that each got.

#766 fix: url builder output includes base path twice
  views/url-builder.html
Labels: service

#767 fix: url builder output includes double forward slash
  lib/routes/v2/docs/url-builder.js
  views/url-builder.html
Labels: service, release:minor

#768 fix: url builder output in production where the hostname env is not set
  lib/routes/v2/docs/url-builder.js
Labels: service, release:patch

#769 Do not use `request.hostname` for url builder output
  lib/routes/v2/docs/url-builder.js
Labels: service, release:patch

#770 deprecate mute_notifications as it is replaced by mute-notifications
  image-sets/fticon/v1/deprecated.json
Labels: service
