Repository Financial-Times/origami-image-service, pull requests merged in 2021-02, with the labels that each got.

#719 Update fticons
  package-lock.json
  package.json
Labels: release:minor, service

#718 update lockfile with changes from `npm update`
  package-lock.json
  package.json
Labels: release:patch, service

#720 Update @financial-times/origami-specialist-title-logos
  package-lock.json
  package.json
Labels: service

#724 simplify our dependabot auto-merge system
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
Labels: service
