Repository Financial-Times/origami-image-service, pull requests merged in 2021-01, with the labels that each got.

#705 Remove reference to old environment variable
  README.md
Labels: service

#706 Bump the logo images dependency
  package-lock.json
  package.json
Labels: release:minor, service

#709 Send to Sentry any errors thrown by the delete images script
  scripts/delete-old-images-from-cloudinary.js
Labels: service

#710 use correct system-code when making the call to the change-api
  .github/workflows/deploy-to-production.yml
  .github/workflows/deploy-to-staging.yml
Labels: service

#711 build(deps): npm audit fix
  package-lock.json
  package.json
Labels: dependencies, security, service
