Repository Financial-Times/origami-image-service, pull requests merged in 2023-03, with the labels that each got.

#821 Do not proxy cloudinary via https
  lib/transformers/cloudinary.js
  test/integration/v2/images-debug.test.js
  test/unit/lib/transformers/cloudinary.test.js
Labels: service, release:patch

#826 [OR-140] Fix Cloudinary SSL Handshake Error, revert back to https
  lib/image-service.js
  lib/transformers/cloudinary.js
  test/integration/v2/images-debug.test.js
  test/unit/lib/image-service.test.js
  test/unit/lib/transformers/cloudinary.test.js
Labels: service, release:patch

#825 Update footer.html
  views/partials/footer.html
Labels: service, release:patch

#827 backstage: add new optimised svg icon
  image-sets/fticon/v1/preferences.svg
Labels: service, release:minor

#819 docs: Remove env docs for RELEASE_LOG_API_KEY
  README.md
Labels: service

#829 Update docs
  README.md
  image-sets/fticon/v1/contributing.md
Labels: documentation, service
