Repository Financial-Times/origami-image-service, pull requests merged in 2023-09, with the labels that each got.

#843 fix: scripts/delete-old-images-from-cloudinary.js [OR-298]
  package-lock.json
  package.json
  scripts/delete-old-images-from-cloudinary.js
Labels: service, release:minor

#844 Update delete-old-images-from-cloudinary.js
  :
  README.md
  scripts/delete-old-images-from-cloudinary.js
Labels: release:patch

#845 backstage: validate uuid before making requests to internal apis
  lib/middleware/get-cms-url.js
  package-lock.json
  package.json
  test/integration/v2/images-raw.test.js
  test/unit/lib/middleware/get-cms-url.test.js
Labels: service

#847 backstage: avoid phishing attacks by returning generic message
  lib/middleware/get-cms-url.js
  test/unit/lib/middleware/get-cms-url.test.js
Labels: service, release:patch

#846 Or 293/upgrade origami service
  package-lock.json
  package.json
Labels: service
